### ISSUE TITLE
se-3-ruby-oo-inheritance-modules$ git push remote: Permission to learn-co-curriculum/phase-3-ruby-oo-inheritance-modules.git denied to tonihaji. fatal: unable to access 'https://github.com/learn-co-curriculum/phase-3-ruby-oo-inheritance-modules.git/': The requested URL returned error: 403

### ISSUE THREAD

**Issue by tonihaji** [learn-co-curriculum/phase-3-ruby-oo-inheritance-inheritance-lab#9]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by lizbur10** [comment]
Hello @tonihaji! This repo is part of Flatiron's Software Engineering curriculum, but the issue template and the people assigned are associated with the Data Science program, so I'm assuming this issue was posted in error. I'm going to go ahead and close it, but feel free to reopen it if you have found a problem with this lesson 💙
